[package]
name = "himalaya_min"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
himalaya-lib = "0.4.0"
native-tls = { version = "0.2.2" }
imap = "2.4.1"
tap = "1.0.1"
mail-parser = "0.6.1"